name: Matrix to build, test & push
on:
  # Launch on manual trigger
  workflow_dispatch:
  # Launch on any push
  push:
  pull_request:
    # Launch on PRs *towards* these branches
    branches:
    - 'release-**'
    - main
    # Not running on "closed" - that is taken care of by "push" (if merged)
    types: [opened, synchronize, reopened]

jobs:
  build-test-push:
    uses: ./.github/workflows/build_test_push.yaml
    strategy:
      fail-fast: true
      matrix:
        info:
          - rondb_version: 21.04.16
            is_latest_rondb_release: false
            glibc_version_x86: 2.17
            glibc_version_arm64: 2.35
            skip_test: true
          - rondb_version: 22.10.3
            is_latest_rondb_release: true
            glibc_version_x86: 2.28
            glibc_version_arm64: 2.28
            skip_test: false
    with:
      rondb_version: ${{ matrix.info.rondb_version }}
      is_latest_rondb_release: ${{ matrix.info.is_latest_rondb_release }}
      rondb_x86_tarball_name: rondb-${{ matrix.info.rondb_version }}-linux-glibc${{ matrix.info.glibc_version_x86 }}-x86_64.tar.gz
      rondb_arm64_tarball_name: rondb-${{ matrix.info.rondb_version }}-linux-glibc${{ matrix.info.glibc_version_arm64 }}-arm64_v8.tar.gz
      skip_test: ${{ matrix.info.skip_test }}
    secrets: inherit
